const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    // orval's output, regenerated by `npm run generate:api`.
    ignores: ['dist/*', 'src/api/generated/*'],
  },
]);
